#!/bin/bash
# Copyright 2016 Georg Felbinger
#
# This file is part of the github project gfelbing/backup.
# 
# gfelbing/backup is free software:
# you can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
# 
# gfelbing/backup is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with gfelbing/backup.
# If not, see http://www.gnu.org/licenses/.

set -e

BASEDIR=$(realpath $(dirname $0))
CONFDIR=~/.config/backup

echo "Loading config variables from $CONFDIR/config"
. $CONFDIR/config

case "$1" in
mount)  . backup-mount
    ;;
run) . backup-run
    ;;
prepare) . backup-prepare
    ;;
umount) . backup-umount;
    ;;
*) echo "Unknown task: '$1'"
   ;;
esac
